<a href="https://colab.research.google.com/github/ronil1508/SOC-2022_QML/blob/main/Weather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing, svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [14]:
dataset= pd.read_csv('/weatherHistory.csv')
print(dataset.shape)

(96453, 12)

In [15]:
print(dataset.describe())

       Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96453.000000              96453.000000  96453.000000
mean         11.932678                 10.855029      0.734899
std           9.551546                 10.696847      0.195473
min         -21.822222                -27.716667      0.000000
25%           4.688889                  2.311111      0.600000
50%          12.000000                 12.000000      0.780000
75%          18.838889                 18.838889      0.890000
max          39.905556                 39.344444      1.000000

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96453.000000            96453.000000     96453.000000     96453.0
mean           10.810640              187.509232        10.347325         0.0
std             6.913571              107.383428         4.192123         0.0
min             0.000000                0.000000         0.000000         0.0
25%             5.828200              116.000000         8.339800         0.0
50%             9.965900              180.000000        10.046400         0.0
75%            14.135800              290.000000        14.812000         0.0
max            63.852600              359.000000        16.100000         0.0

       Pressure (millibars)
count          96453.000000
mean            1003.235956
std              116.969906
min                0.000000
25%             1011.900000
50%             1016.450000
75%             1021.090000
max             1046.380000

In [16]:
dataset.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [17]:
dataset1 = dataset[['Temperature (C)','Humidity']]
dataset1.head()

   Temperature (C)  Humidity
0         9.472222      0.89
1         9.355556      0.86
2         9.377778      0.89
3         8.288889      0.83
4         8.755556      0.83

In [19]:
X = np.array(dataset1['Temperature (C)']).reshape(-1,1)
y = np.array(dataset1['Humidity']).reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [20]:
lr = LinearRegression()
lr.fit(X_train,y_train)
print(lr.score(X_train,y_train))
print(lr.score(X_test,y_test))

0.4009665003345476
0.39481605751869386

We can clearly see that linear regression underfits the triaining data

Now we perform multi-variable linear regression

In [21]:
dataset2 = dataset[['Temperature (C)','Humidity','Pressure (millibars)']]
dataset2.head()

   Temperature (C)  Humidity  Pressure (millibars)
0         9.472222      0.89               1015.13
1         9.355556      0.86               1015.63
2         9.377778      0.89               1015.94
3         8.288889      0.83               1016.41
4         8.755556      0.83               1016.51

In [22]:
X = np.array(dataset2[['Temperature (C)','Pressure (millibars)']])
y = np.array(dataset2['Humidity'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [23]:
lr.fit(X_train,y_train)
print(lr.score(X_train,y_train))
print(lr.score(X_test,y_test))

0.39832861576298506
0.40539076024977583

Multi variable linear regression also underfits the data.